steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'varniah/sit737-app:v2', '.']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker login -u varniah -p $_DOCKER_PASS && docker push varniah/sit737-app:v2'

options:
  logging: NONE